### ISSUE TITLE
night mode

### ISSUE THREAD

**Issue by jangorecki** [ess-intro/ess-intro#1]
What I find useful in different desktop apps it to have easy possibility to switch between day and night mode. So in the night I can use dark theme to make eyes not getting tired that fast.
This feature, if exists, could probably be mentioned somewhere.

**Comment by eddelbuettel** [comment]
:man_shrugging: -- themes are AFAIK orthogonal to modes (I live in [nord](https://github.com/arcticicestudio/nord-emacs) and really love it for Emacs and Gnome Terminal) so I don't really think this a talk topic -- unless we "eventually" get to sprucing up and personalising Emacs.  A little far from first topics of introducing ESS in my book.

**Comment by jangorecki** [comment]
I understand that this is a styling/theme-ing/personalizing subject, yet the most users looking for a night mode, will not be interested in styles or themes per se but just a simple day/night switch. Anyway looking forward for materials in this repo.

**Comment by eddelbuettel** [comment]
It's like asking for chocolate milk.  Nothing wrong with the question per se, but a tenuous-at-best relationship to what this repo and initiative are about.
