### ISSUE TITLE
New cross-post?

### ISSUE THREAD

**Issue by eddelbuettel** [ess-intro/ess-intro#13]
I just recorded and posted a short video on using byobu (using tmux underneath) to collaborate on files, and via ESS / Emacs also execute.  Short blog post is here:  http://dirk.eddelbuettel.com/blog/2021/06/09#033_collaborate_via_byobu

I would be happy to cross-link from our title page, but if anybody feels that it strays too far from the core mission of ESS Intro I would understand too---it really sits at the intersection.

**Comment by lebensterben** [comment]
tmux can get new users really confused.

ssh + multi-tty is a simpler solution in my opinion.

The only setup is SSH server/client, and Emacs running in daemon mode on the SSH server.

In addition, this is not only for pair programming, you can also have multiple devices connect to the same Emacs session to have multiple displays.

**Comment by eddelbuettel** [comment]
This is now fully off-toic but you may not be aware that I always argue in favour of byobu (and the nicer / saner UI is one reason).  I have a few posts from last year here which may provide context:   https://dirk.eddelbuettel.com/blog/code/t4/ -- see in particular episode 4, 5 and 6.

**Comment by lebensterben** [comment]
My point is the idea of pair programming within Emacs would be interesting to many readers, but I prefer a more Emacs-centric approach.

Emacs itself already has multiplexing capability and requires minimum setup, comparing to Tmux or Byobu.

**Comment by eddelbuettel** [comment]
So maybe hit the wiki, add a new talk proposal, write and shoot it ... ?

**Comment by lebensterben** [comment]
nah. I'm more interested in getting ideas from discussions and add them to Spacemacs, to which I'm a co-maintainer.

**Comment by plantarum** [comment]
I think this is really cool, and I would be happy to see it 
cross-linked. I didn't know anything like this was possible, but 
now that I do I can see using this in my teaching, especially 
while we're still locked down here. 

I don't know about other options, but I think a tutorial that 
exists is already much better than any tutorial that doesn't 
exist!

ty

**Comment by lebensterben** [comment]
@plantarum There are plenty of tutorials already. For example, https://enigmacurry.com/2007/05/24/multi-tty-emacs-on-gentoo-and-ubuntu/

**Comment by eddelbuettel** [comment]
Dear @lebensterben are you aware that you are hijacking a thread that had a different topic?  You made your point, we understand, but could you now let us discuss what the thread was made for?   Thanks for your understanding.  And no need to reply here.

**Comment by eddelbuettel** [comment]
Thanks for the encouragement @plantarum !  I'll wait for day or two for possible 'maybe not' sentiment from ess-intro but otherwise I'll add it.  If it is deemed out of scope later we can always remove it...

**Comment by lebensterben** [comment]
No. I'm not hijacking anything. My comments are directed towards the topic here, that whether the mentioned screencast should be cross-linked.

And I've clearly stated that the idea of collaborative editing, or pair programming, is of interest to many readers, but the implementation introduced here is marginally related to Emacs.

Since this repository is about introducing R users to ESS, I recommend to use multi-tty as it's more Emacs centric and has fewer setups required.

Why I don't want to contribute a new tutorial on this topic? Because it's dead simple and trivial in my opinion, let alone there are other tutorials online.

**Comment by eddelbuettel** [comment]
Now added to the 'title page', and I moved the repo (once created for joint work, ended up only me comitting) into the org too. 

So I close this now.
