### ISSUE TITLE
presenting at EmacsConf 2021???

### ISSUE THREAD

**Issue by aezarebski** [ess-intro/ess-intro#15]
There are <10 minute talks at https://emacsconf.org/2021/cfp/ if someone (@eddelbuettel) associated with the ess-intro stuff was feeling brave, this might be a way to get a bit more mileage out of the work that has already been done and to tell a nice story of community.

**Comment by eddelbuettel** [comment]
Nice one.  I actually saw a tweet re emacsconf and didn't even click myself.  Happy to aim for a (joint ?) 10 min slot.  You in?

**Comment by aezarebski** [comment]
yer, definitely not putting my hand up to do the actual speaking, (not sure that would actually help in anyway), but happy to lend a hand with preparation if it would help.

**Comment by eddelbuettel** [comment]
We can close this now.
