### ISSUE TITLE
trouble editing wiki pages

### ISSUE THREAD

**Issue by aezarebski** [ess-intro/ess-intro#2]
I would like to be able to edit the wiki. I cannot see any UI elements to allow me to either edit existing wiki pages or add new ones.  It would be nice if we could edit these as easy as the collabedit page. It seems like this should be possible based on the information at the following links

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-or-editing-wiki-pages

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis

Am I missing something obvious about how to edit the wiki?

**Comment by eddelbuettel** [comment]
Hm. The intend and plan was to allow this.  Now, while I am reasonably familar with GitHub I had not fiddled with this either way, _i.e._ I have neither enable nor disable it assumed all of us in the org would have access.  I clearly do :)  

Anybody have any thoughts?

**Comment by eddelbuettel** [comment]
Found it!  Default access for wiki was 'write for all who can push' yet somehow you all only had read access to the ess-intro (main ?) initial repo I created.  That should now fixed.

**Comment by aezarebski** [comment]
Excellent! Thanks :+1:

**Comment by eddelbuettel** [comment]
Ok to close then?
